### PR TITLE
Update gt4py on August 19, 2022

### PR DESCRIPTION
**Pull request by jdahm**
## Purpose

Update gt4py to the `gridtools/gt4py:master` [e61c49a](https://github.com/GridTools/gt4py/commit/e61c49aad7b7783b40249e8d27c0b1d33badc70b).

### CODE REVIEW

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
Hmm, first it's
```
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorDevicesUnavailable: all CUDA-capable devices are busy or unavailable
```
now it's
```
12:13:25 E   ModuleNotFoundError: No module named 'xarray'
12:13:25 + '[' 4 -ne 0 ']'
12:13:25 + exitError 1510 73 'problem while executing script /tmp/workspace/pace-util_PR/slave/gce-1p100-v4/target/gpu/pace-util/.jenkins/actions/test.sh'
12:13:25 + rm -f /tmp/tmp..4753
12:13:25 + echo 'ERROR 1510: problem while executing script /tmp/workspace/pace-util_PR/slave/gce-1p100-v4/target/gpu/pace-util/.jenkins/actions/test.sh'
12:13:25 ERROR 1510: problem while executing script /tmp/workspace/pace-util_PR/slave/gce-1p100-v4/target/gpu/pace-util/.jenkins/actions/test.sh
12:13:25 + echo 'ERROR     LOCATION=.jenkins/jenkins.sh'
12:13:25 ERROR     LOCATION=.jenkins/jenkins.sh
12:13:25 + echo 'ERROR     LINE=73'
12:13:25 ERROR     LINE=73
12:13:25 + exit 1510
```

Thanks, daint!

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
Jenkins - please test the correct branch. This is using the branch from another PR...

**Review by FlorianDeconinck — APPROVED** [review]

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
re-launched Jenkins because the last run errored on the 54 rank test with

```MPICH2 ERROR [Rank 48] [job id 40795605] [Tue Aug 23 18:42:08 2022] [c5-2c2s9n1] [nid04965] - MPID_nem_gni_check_localCQ(): GNI_CQ_EVENT_TYPE_POST had error (SOURCE_SSID:AT_MDD_INV:CPLTN_DREQ)```

**Comment by FlorianDeconinck** [comment]
That MPI error is definitely jenkins being jenkins

**Pull request merged**
