### PR TITLE
fix grid tests for 54 ranks 

### PR DESCRIPTION
**Pull request by rheacangeo**
### Purpose
To have the regressions-cron test in CI passing, specifically getting the new grid tests to work for c12_54ranks_standard. 
* GnomonicGrid and MirrorGrid tests run on the global tile and are changed to be done with. numpy only (no quantities needed).

### CODE REVIEW

**Comment by rheacangeo** [comment]
Closing this for now, as @oelbert pointed out, some of these threshold shifts are worrying and warrant a fuller investigation. Plus the fortran data generation is broken. We'll open a new PR when we get this sorted.

**Comment by rheacangeo** [comment]
Turning the PR back on to at least fix the 54 rank tests

**Review by oelbert — APPROVED** [review]
Looks good to me

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Pull request merged**
