### PR TITLE
Move ci project to go31

### PR DESCRIPTION
**Pull request by jdahm**
## Purpose

Update Jenkins to use the new go31 project on CSCS.
Add `skip_test` option to the translate test for faulty `dace:gpu` FVSubgridZ

### CODE REVIEW

**Comment by jdahm** [comment]
launch jenkins

**Review by oelbert — APPROVED** [review]
LGTM

**Comment by FlorianDeconinck** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Comment by FlorianDeconinck** [comment]
launch jenkins

**Pull request merged**
