### PR TITLE
Fix microphysics init when using GPU

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
## Purpose

When SDFG is built all arrays have a promise device (GPU, CPU) and the runtime needs to match this. In microphysics a setup step was moving an array on CPU using `numpy` but promising a GPU via the `to_gpu`

Better solution would be to have a less aggressive `to_gpu` pass on the orchestration pipeline.

This quicker fix makes sure the promised array is on the right device.

## Code changes:

- Use `numpy_module` which is `cp` under GPU

## Requirements changes:

N/A

## Infrastructure changes:

N/A

## Checklist
Before submitting this PR, please make sure:

- [x] You have followed the coding standards guidelines established at [Code Review Checklist](https://drive.google.com/file/d/1R0nqOxfYnzaSdoYdt8yjx5J482ETI2Ft/view?usp=sharing).

### CODE REVIEW

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Review by elynnwu — APPROVED** [review]

**Comment by FlorianDeconinck** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Pull request merged**
