### PR TITLE
Update gt4py

### PR DESCRIPTION
**Pull request by jdahm**
## Purpose

Keep up to date with gt4py development.

## Code changes:

- Updates the gt4py submodule to the tip of `ai2cm/gt4py:main`.

### CODE REVIEW

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Review by FlorianDeconinck — APPROVED** [review]
LGTM

**Pull request merged**
