### PR TITLE
Fix/jenkins cache setup

### PR DESCRIPTION
**Pull request by elynnwu**
## Purpose

This PR fixes fv3core cache setup plan.

## Code changes:

- Deleted `fix_cache.py` since this change is reflected in the latest gt4py version
- `compile.py` and `dynamics.py`: explicitly passes `data_dir` instead of relying on global `args`
- `collect_memory_usage_data.py`: update to conform to new serialized data path

## Checklist
Before submitting this PR, please make sure:

- [x] You have followed the coding standards guidelines established at [Code Review Checklist](https://paper.dropbox.com/doc/Code-Review-Checklist--BD7zigBMAhMZAPkeNENeuU2UAg-IlsYffZgTwyKEylty7NhY).

### CODE REVIEW

**Comment by elynnwu** [comment]
Jenkins cache setup:
https://jenkins.ginko.ch/view/pace/job/pace-fv3core-cache-setup/267/

**Comment by twicki** [comment]
lgtm

**Comment by elynnwu** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Review by twicki — APPROVED** [review]
LGTM

**Comment by elynnwu** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Pull request merged**
