### PR TITLE
Add print statements when fetching gt_cache

### PR DESCRIPTION
**Pull request by elynnwu**
In this PR, we add print statements to indicate if gt_cache are fetched from disk on daint. Currently, there is no indication in jenkins on whether the caches are fetched successfully.

### CODE REVIEW

**Review by twicki — APPROVED** [review]
lgtm

**Comment by elynnwu** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Comment by elynnwu** [comment]
launch jenkins

**Pull request merged**
