### PR TITLE
Update gt4py caching scripts to upload to/download from GCS

### PR DESCRIPTION
**Pull request by mcgibbon**
## Purpose

We'd like to test our compiled backends on google cloud, but this is currently slow due to caches not being available. This PR uploads caches to google cloud and downloads them if they are not available on the local machine.

## Infrastructure changes:

- .jenkins/generate_caches.sh is updated to upload cache tars to the gs://fv3core-gt-cache cloud bucket
- .jenkins/fetch_caches.sh is updated to download cache tars from the gs://fv3core-gt-cache cloud bucket if they are not present on the local machine

## Checklist
Before submitting this PR, please make sure:

- [ ] You have followed the coding standards guidelines established at [Code Review Checklist](https://paper.dropbox.com/doc/Code-Review-Checklist--BD7zigBMAhMZAPkeNENeuU2UAg-IlsYffZgTwyKEylty7NhY).
- [ ] Docstrings and type hints are added to new and updated routines, as appropriate
- [ ] All relevant documentation has been updated or added (e.g. README, CONTRIBUTING docs)
- [ ] For each public change and fix in `pace-util`, HISTORY has been updated
- [ ] Unit tests are added or updated for non-stencil code changes

Additionally, if this PR contains code authored by new contributors:

- [ ] The names of all the new contributors have been added to CONTRIBUTORS.md

### CODE REVIEW

**Review by elynnwu — COMMENTED** [review]
I'm wondering if it is okay to use caches generated from daint on gce if the gt4py version is the same? Does the gcc version not matter?

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
Closing PR, @elynnwu is right and these caches will not transfer between platforms since they link to local shared libraries.

**Pull request closed without merging**
