### PR TITLE
Run test_driver on large resource class

### PR DESCRIPTION
**Pull request by mcgibbon**
## Purpose

Currently we are experiencing intermittent failures of `test_driver` on CircleCI, and are hitting CPU caps on the machine. This PR updates the resource class for that job from medium to large to increase CPU availability.

## Infrastructure changes:

- updated resource class for CircleCI test_driver job to `large`

## Checklist
Before submitting this PR, please make sure:

- [x] You have followed the coding standards guidelines established at [Code Review Checklist](https://drive.google.com/file/d/1R0nqOxfYnzaSdoYdt8yjx5J482ETI2Ft/view?usp=sharing).
- [x] Docstrings and type hints are added to new and updated routines, as appropriate
- [x] All relevant documentation has been updated or added (e.g. README, CONTRIBUTING docs)
- [x] For each public change and fix in `pace-util`, HISTORY has been updated
- [x] Unit tests are added or updated for non-stencil code changes

### CODE REVIEW

**Review by FlorianDeconinck — COMMENTED** [review]
*STAMP noise*

**Comment by FlorianDeconinck** [comment]
launch jenkins

**Review by FlorianDeconinck — COMMENTED** [review]
Bad clicks, still stamped

**Review by FlorianDeconinck — APPROVED** [review]

**Comment by mcgibbon** [comment]
Jenkins failed, but I patched this in to the 54rank test PR which just merged so no longer needed.

**Pull request closed without merging**
