### PR TITLE
Remove INSTALL_FLAGS environment variables

### PR DESCRIPTION
**Pull request by mcgibbon**
## Purpose

This PR updates the virtualenv install scripts to use the -e flag directly instead of passing it from a higher level script, for clarity. This flag is never configured and has been constant.

## Infrastructure changes:

- removed PACE_INSTALL_FLAGS and FV3CORE_INSTALL_FLAGS environment variables from install_virtualenv.sh scripts, instead using `-e` directly.

## Checklist
Before submitting this PR, please make sure:

- [ ] You have followed the coding standards guidelines established at [Code Review Checklist](https://paper.dropbox.com/doc/Code-Review-Checklist--BD7zigBMAhMZAPkeNENeuU2UAg-IlsYffZgTwyKEylty7NhY).
- [ ] Docstrings and type hints are added to new and updated routines, as appropriate
- [ ] All relevant documentation has been updated or added (e.g. README, CONTRIBUTING docs)
- [ ] For each public change and fix in `pace-util`, HISTORY has been updated
- [ ] Unit tests are added or updated for non-stencil code changes

Additionally, if this PR contains code authored by new contributors:

- [ ] The names of all the new contributors have been added to CONTRIBUTORS.md

### CODE REVIEW

**Review by elynnwu — APPROVED** [review]
lgtm!

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
launch jenkins

**Comment by mcgibbon** [comment]
It looks like this PR breaks the physics tests for unknown reasons. This may be even more of a reason to remove this variable (because of it, we don't understand what the test scripts are doing), but because we don't understand what's going on it will take more time to fix.

**Comment by mcgibbon** [comment]
Closing as this was fixed in another way in another PR.

**Pull request closed without merging**
